import OpenAI from "openai"
import { ChatCompletionMessageParam } from "openai/resources/chat/completions"
import { savePoseAnalysis } from "@/lib/database"
import { poseCache } from "@/lib/cache"

const systemPrompt = `Generate MMD pose data from description.`

const userPrompt = `Description: {description}`

const temperature = 0.1
const topP = 0.1

export async function POST(request: Request) {
  if (!process.env.AI_MODEL || !process.env.AI_API_KEY || !process.env.AI_API_BASE_URL) {
    return Response.json({ error: "Missing required environment variables" }, { status: 500 })
  }

  try {
    const { description } = await request.json()

    // Check cache first
    const cachedResult = await poseCache.get(description, process.env.AI_MODEL!, temperature, topP)

    if (cachedResult) {
      // Save to database for analysis (non-blocking)
      savePoseAnalysis({
        description,
        result: JSON.parse(JSON.stringify(cachedResult)),
        aiModel: process.env.AI_MODEL,
        temperature,
        topP,
      })
      return Response.json({
        result: cachedResult,
        cached: true,
      })
    }

    // Cache miss - proceed with AI generation
    const provider = new OpenAI({
      apiKey: process.env.AI_API_KEY,
      baseURL: process.env.AI_API_BASE_URL,
    })

    // Use the exact format from fine-tuning data
    const messages: ChatCompletionMessageParam[] = [
      { role: "system", content: systemPrompt },
      {
        role: "user",
        content: userPrompt.replace("{description}", description),
      },
    ]

    const response = await provider.chat.completions.create({
      model: process.env.AI_MODEL,
      messages,
      temperature,
      top_p: topP,
    })

    let result
    try {
      result = JSON.parse(
        response.choices[0].message.content ??
          '{"description": "", "face": [], "movableBones": [], "rotatableBones": []}'
      )
      const resultAnalysis = JSON.parse(JSON.stringify(result))
      resultAnalysis.description = description

      // Cache the result for future requests
      await poseCache.set(description, resultAnalysis, process.env.AI_MODEL!, temperature, topP)

      // Save to database for analysis (non-blocking)
      savePoseAnalysis({
        description,
        result: resultAnalysis,
        aiModel: process.env.AI_MODEL,
        temperature,
        topP,
      })
    } catch {
      return Response.json(
        {
          error: "Invalid JSON generated by AI",
          result: { description: "", face: [], movableBones: [], rotatableBones: [] },
          raw: response.choices[0].message.content,
        },
        { status: 500 }
      )
    }

    return Response.json({
      result,
      cached: false,
    })
  } catch (error) {
    console.error("Error generating pose:", error)
    return Response.json(
      { error: "Failed to generate pose", result: { description: "", face: [], movableBones: [], rotatableBones: [] } },
      { status: 500 }
    )
  }
}
