import OpenAI from "openai"
import { ChatCompletionMessageParam } from "openai/resources/chat/completions"

const systemPrompt = `You are an expert in MMD (MikuMikuDance) pose generation. Given a description of a pose, you generate the corresponding bone rotations, positions, and facial morphs in JSON format.`

const userPrompt = `Generate MMD pose data for: {description}`

export async function POST(request: Request) {
  if (!process.env.AI_MODEL || !process.env.AI_API_KEY || !process.env.AI_API_BASE_URL) {
    return Response.json({ error: "Missing required environment variables" }, { status: 500 })
  }

  try {
    const { description } = await request.json()

    const provider = new OpenAI({
      apiKey: process.env.AI_API_KEY,
      baseURL: process.env.AI_API_BASE_URL,
    })

    // Use the exact format from fine-tuning data
    const messages: ChatCompletionMessageParam[] = [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt.replace("{description}", description || "standing pose") },
    ]

    const response = await provider.chat.completions.create({
      model: process.env.AI_MODEL,
      messages,
      // temperature: 0, // Most deterministic
      top_p: 0.1, // Very focused sampling
    })

    let result
    try {
      result = JSON.parse(
        response.choices[0].message.content ??
          '{"description": "", "face": [], "movableBones": [], "rotatableBones": []}'
      )
    } catch {
      return Response.json(
        {
          error: "Invalid JSON generated by AI",
          result: { description: "", face: [], movableBones: [], rotatableBones: [] },
          raw: response.choices[0].message.content,
        },
        { status: 500 }
      )
    }

    return Response.json({
      result,
    })
  } catch (error) {
    console.error("Error generating pose:", error)
    return Response.json(
      { error: "Failed to generate pose", result: { description: "", face: [], movableBones: [], rotatableBones: [] } },
      { status: 500 }
    )
  }
}
